base:
  project: simple-dvc-project
  random_state: 42
  target_col: quality
  test_size: 0.2

data_source:
  s3_source: https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv

artifacts: 
  artifacts_dir: artifacts
  raw_local_data_dir: artifacts/raw_local_data_dir
  raw_local_data: artifacts/raw_local_data_dir/data.csv

  split_data: 
    processed_data_dir: artifacts/processed_data
    train_path: artifacts/processed_data/train.csv
    test_path: artifacts/processed_data/test_data.csv

  reports:
    reports_dir: artifacts/reports
    params: artifacts/reports/params.json
    scores: artifacts/reports/scores.json

  model_dir: artifacts/saved_models
  model_path: artifacts/saved_models/model.joblib

estimators:
  Elasticnet:
    params: 
      alpha: 0.7
      l1_ratio: 0.4